FROM node:22.5-alpine

WORKDIR /app

COPY package*.json ./.

ENV MARIADB_HOST=${MARIADB_HOST}
ENV MARIADB_PORT=${MARIADB_PORT}
ENV MARIADB_DATABASE=${MARIADB_DATABASE}
ENV MARIADB_USER=${MARIADB_USER}
ENV MARIADB_PASSWORD=${MARIADB_PASSWORD}

RUN npm install -g pnpm

RUN pnpm install

COPY . .

EXPOSE 5000

CMD ["pnpm","start"]
